### ISSUE TITLE
hyperparameters for results described in paper

### ISSUE THREAD

**Issue by dhecloud** [allenai/winogrande#2]
Hi, what are the specific hyperparameters for the results achieved in the paper (79.3 for roberta and 65.8 for bert)? 
I saw the mention of the grid search but the exact values leading to the results were not mentioned. Thank you!

**Comment by keisks** [comment]
Hi, thank you for reaching out.
The hyper-parameters for RoBERTa and BERT are as follows.

- RoBERTa
```
LEARNING_RATE: 1e-5
MODEL_NAME_OR_PATH: roberta-large
NUM_EPOCHS: 8
SEED: 11262
TRAIN_BATCH_SIZE: 16
```

- BERT
```
LEARNING_RATE: 1e-5
MODEL_NAME_OR_PATH: bert-large-uncased
NUM_EPOCHS: 8
SEED: 1873
TRAIN_BATCH_SIZE: 8
```

I also uploaded the fine-tuned model (and config) files to [our project page](http://winogrande.allenai.org/). 
 
I hope this helps :)

**Comment by dhecloud** [comment]
> Hi, thank you for reaching out.
> The hyper-parameters for RoBERTa and BERT are as follows.
> 
> * RoBERTa
> 
> ```
> LEARNING_RATE: 1e-5
> MODEL_NAME_OR_PATH: roberta-large
> NUM_EPOCHS: 8
> SEED: 11262
> TRAIN_BATCH_SIZE: 16
> ```
> 
> * BERT
> 
> ```
> LEARNING_RATE: 1e-5
> MODEL_NAME_OR_PATH: bert-large-uncased
> NUM_EPOCHS: 8
> SEED: 1873
> TRAIN_BATCH_SIZE: 8
> ```
> 
> I also uploaded the fine-tuned model (and config) files to [our project page](http://winogrande.allenai.org/).
> 
> I hope this helps :)

Thank you very much! :)

**Comment by cuichenx** [comment]
Hi, thank you for posting the hyper-parameters. Are these for the "xl" dataset? Do you use the same hyperparameters for the smaller datasets or are they different? Thanks!

**Comment by keisks** [comment]
Yes, these are for the `XL` dataset.
As you may know, transformer models like BERT and RoBERTa are very sensitive to hyper-parameters. 

- XS
```
LEARNING_RATE: 1e-5
NUM_EPOCHS: 5
SEED: 5006
TRAIN_BATCH_SIZE: 16
```

- S
```
LEARNING_RATE: 1e-5
NUM_EPOCHS: 5
SEED: 30693
TRAIN_BATCH_SIZE: 8
```

- M
```
LEARNING_RATE: 1e-5
NUM_EPOCHS: 8
SEED: 23680
TRAIN_BATCH_SIZE: 16
```

- L
```
LEARNING_RATE: 1e-5
NUM_EPOCHS: 5
SEED: 26069
TRAIN_BATCH_SIZE: 16
```
