### ISSUE TITLE
Reproducing Transfer-Learning from WinoGrande to WSC

### ISSUE THREAD

**Issue by slowwavesleep** [allenai/winogrande#5]
Hi,

I'm trying to reproduce the results from the paper _WINOGRANDE: An Adversarial Winograd Schema Challenge at Scale_, more specifically _6 Using WINOGRANDE as a Resource_, where `77.6` accuracy is achieved on WSC task by a model finetuned on WinoGrande.

So far I tried running `sample_training.sh` and then feeding the output model to the `sample_training_superglue-wsc.sh` script. I got the following error:

```
RuntimeError: Error(s) in loading state_dict for RobertaForSequenceClassification:
  size mismatch for classifier.out_proj.weight: copying a param with shape torch.Size([1, 1024]) from checkpoint, the shape in current model is torch.Size([2, 1024]).
  size mismatch for classifier.out_proj.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([2]).
```

Evidently, the classification heads are different for these two tasks. I was wondering whether it is possible to load the model without classification head using the code in the repository? Can you help me with that?

Also, would you mind sharing the hyperparameters used to achieve the results from the paper?

**Comment by keisks** [comment]
Hi @slowwavesleep, thank you for the question. 

Before answering the question, it seems that you are looking at [the old version of paper](https://arxiv.org/abs/1907.10641v1). The latest version is available [here](https://arxiv.org/abs/1907.10641).

>So far I tried running `sample_training.sh` and then feeding the output model to the `sample_training_superglue-wsc.sh` script. I got the following error:

It looks like you are using wrong files to train (and predict).
If you want to train a model and predict with the model, use `sample_training.sh` and `sample_prediction.sh`. If you train and predict on "superglue-wsc", use `sample_training_superglue-wsc.sh` and `sample_prediction_superglue-wsc.sh`. 

>Also, would you mind sharing the hyperparameters used to achieve the results from the paper?

Yes, I'm happy to share it. Which result do you refer to?

**Comment by slowwavesleep** [comment]
Thank you for the reply and sorry for confusion.
 
I think I might have misinterpreted the purpose of the training files. I was under the impression that `sample_train.sh` is specifically for training the model on just the WinoGrande task and `sample_training_superglue-wsc.sh` is for training on _just the SuperGLUE WSC_ (i.e. without an intermediate WinoGrande step). Please correct me if I'm wrong.

In any case, what I wanted to do is to reproduce specifically this result:


![image](https://user-images.githubusercontent.com/44175589/112273690-ae277c00-8c8e-11eb-98d3-aeb0de05f2c9.png)


As I understand, it is achieved by first training the model on the WinoGrande task and then reusing the weights and training the model on the SuperGLUE WSC task.

Regarding the version of the article, I realized that I'm refering to the old one somewhat recently and there's an additional question since you mentioned it. What prompted such a boost in performance on the original WSC ( `77.6 -> 90.1`)? 

The thing is that I'm trying various tricks to get above a certain threshold on SuperGLUE WSC, but the best score I can get so far is below `70`, so I'm trying to figure out what I'm may be missing. Which is why I'm asking you to share the hyperparameters used to achieve the result in SuperGLUE WSC on the screenshot above.

**Comment by keisks** [comment]
> I was under the impression that sample_train.sh is specifically for training the model on just the WinoGrande task and sample_training_superglue-wsc.sh is for training on just the SuperGLUE WSC (i.e. without an intermediate WinoGrande step).

Oh, I see. It is confusing, indeed. I'll add explanation in the README. Thank you!!

> In any case, what I wanted to do is to reproduce specifically this result:
> As I understand, it is achieved by first training the model on the WinoGrande task and then reusing the weights and training the model on the SuperGLUE WSC task.

Yes, you are right. Regarding the model for reproducing the results (for SuperGlue-wsc), the best model used the following hyperparameters: `learning rate=1.0e-5, epoch=5.0, seed=7007,  batch=8.0`. (The model can be downloaded from [this link](https://storage.googleapis.com/ai2-mosaic/public/winogrande/winogrande-superglue-wsc.zip).)

> Regarding the version of the article, I realized that I'm refering to the old one somewhat recently and there's an additional question since you mentioned it. What prompted such a boost in performance on the original WSC ( 77.6 -> 90.1)?

The main difference is `BERT (old version) vs. RoBERTa (latest version)`. Another difference is that the noise in the dataset was removed in the latest version.

I hope this helps.

**Comment by slowwavesleep** [comment]
So to reiterate,  `sample_training_superglue-wsc.sh` does both WinoGrande and SuperGLUE WSC, is that correct?

Also, there's another thing I'd like to ask you. One notable difference between the original WSC and the SuperGLUE version is that the SuperGLUE version drops the second option from the examples. The way I see it, it makes the problem somewhat harder. Some solutions, such as Facebook's RoBERTa submit on the SuperGLUE leaderboard, involve mining additional candidate NPs from the sentences, as explained [here](https://github.com/pytorch/fairseq/tree/master/examples/roberta/wsc). Supposedly, that boosts the performance. Do I understand it correctly that the result in the paper is achieved without these sort of tricks?

**Comment by keisks** [comment]
> So to reiterate, sample_training_superglue-wsc.sh does both WinoGrande and SuperGLUE WSC, is that correct?

It trains a model in SuperGLEU-WSC format, True/False binary choice instead of choosing a right answer, meaning that WinoGrande dataset needs to be formatted in the same way. For example, the following WinoGrande instance 
```
{"sentence": "Katrina had the financial means to afford a new car while Monica did not, since _ had a high paying job.", "option1": "Katrina", "option2": "Monica", "answer": "1"}
```

becomes two examples in the SuperGLEU-WSC (True/False) format below.

```
{"sentence1": "Katrina had the financial means to afford a new car while Monica did not, since ", "sentence2": "Katrina had a high paying job.", "label": "1"}
{"sentence1": "Katrina had the financial means to afford a new car while Monica did not, since ", "sentence2": "Monica had a high paying job.", "label": "0"}
```

Please note that [the original WSC](http://commonsensereasoning.org/winograd.html) (and WinoGrande) is multiple choice questions (mostly the number of options=2).  

For the SuperGLEU-WSC experiments in our paper, we fine-tuned a model with WinoGrande in the True/False format, and additionally fine-tuned with the SuperGLEU-WSC dataset.

I hope this answers your question.

**Comment by vaskonov** [comment]
@keisks I wonder if WinoGrande can be downloaded in the True/False format, alternatively, how I can convert WinoGrande into True/False format?
