### ISSUE TITLE
Error in the description of context and option in paper?

### ISSUE THREAD

**Issue by xiaoouwang** [allenai/winogrande#6]
Hello!

I'm trying to replicate your paper and I'm wondering if there is an error in the description of sentence split:

So this is the original sentence:

> The input format becomes [CLS] context [SEP] option [SEP]; e.g., The trophy doesn’t fit into the brown suitcase because the ___  [SEP] is too large. [SEP] (The blank is filled with either option 1 or 2)

However if i understand correctly it should be 

> The trophy doesn’t fit into the brown suitcase because the [SEP] ___   is too large.

```python
sentence = "Sarah was a much better surgeon than Maria so _ always got the easier cases"
conj = "_"
idx = sentence.index(conj)
context = sentence[:idx]
option_str = "_ " + sentence[idx + len(conj):].strip()
print(context)
print(option_str)
```

Sarah was a much better surgeon than Maria so 
_ always got the easier cases

Fantastic efforts by the way!

Xiaoou

**Comment by keisks** [comment]
Hi @xiaoouwang, good catch. Thank you for letting me know. Please follow the format in the codebase.
